### ISSUE TITLE
[Enhancement] Option to change name of tag/category

### ISSUE THREAD

**Issue by chocolatechipcats** [jullebarge/Playnite_EgsFreeGamesChecker#1]
Useful plugin!

It would be helpful if the user could select the name of the added tag/category, either in the extension setings or a dialog in the add action; I have a pre-existing `[Epic] Giveaways` tag that I'd prefer to use. 

Thanks in advance.

**Comment by jullebarge** [comment]
It's not easy to do in a script extension, as you can't add an option page. 
For now, you can change the name of the tag by opening the installation folder of the extension and change it in the localisation file:
![image](https://user-images.githubusercontent.com/11553167/212169531-3d9839b6-d96d-4d7c-84f3-b7ad979aff7f.png)

**Comment by chocolatechipcats** [comment]
That'll work. Thank you!

Feel free to close this if you'd like.

**Comment by chocolatechipcats** [comment]
For future people: You need to restart Playnite for changes to the plugin to actually work. Oops...

**Comment by jullebarge** [comment]
No need to restart, you can use F12 to refresh scripts ;)
Be careful, each time the extension will be updated, you'll have to change your tag back in the file.

I'll try to find a better way to handle that.

**Comment by jullebarge** [comment]
The option to choose the tag name (and save it) as been added in 0.2 release
